apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
 name: web
 labels: # Метки в формате key: value
   app: web
spec: # Описание Pod
 containers: # Описание контейнеров внутри Pod
 - name: web
   image: korschunoffk/kuberhomework1:v2
   readinessProbe: # Добавим проверку готовности
     httpGet: # веб-сервера отдавать
       path: /index.html # контент
       port: 8000
   livenessProbe: 
     tcpSocket:
       port: 8000
   volumeMounts:
   - name: app
     mountPath: /app
 initContainers:
 - name: install
   image: busybox:1.31.0
   command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
   volumeMounts:
   - name: app
     mountPath: "/app"
 volumes:
 - name: app
   emptyDir: {}