apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
 name: web
 labels: # Метки в формате key: value
   app: web
spec: # Описание Pod
 containers: # Описание контейнеров внутри Pod
 - name: web-container
   image: korschunoffk/kuberhomework1:v2
   volumeMounts:
   - name: app
     mountPath: /app
 initContainers:
 - name: install
   image: busybox:1.31.0
   command:
   - wget
   - "-O"
   - "/app/index.html"
   - http://info.cern.ch
   volumeMounts:
   - name: app
     mountPath: "/app"
 volumes:
 - name: app
   emptyDir: {}